### ISSUE TITLE
Incompatibility?

### ISSUE THREAD

**Issue by keesj** [wallento/wavedrompy#46]
Hello, I am trying to render the following using a pip installed wavedrompy 

```
{signal: [
    {    name: 'clk',        wave: 'p..pp......p'},
    {name: 'input_ready',    wave:    '010.........', node:'............', },
    {name: 'signalanalisys', wave: '0...3....0..'   , node:'............', data: ["running"]},
    {                                                 node:'.A..B.......', },
    {name: 'output_ready',    wave:   '0........10.', },
  
],
  edge: [
    'A<->B delay'
]
}
```

On the online version this works nicely 
![image](https://github.com/user-attachments/assets/3c6060db-9d12-44ea-b95e-d62eef3ab90b)

But when I tried to render it using wavedrompy  (from the command line) I am getting this error:
```
Traceback (most recent call last):
  File "/home/keesj/.venv/bin/wavedrompy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/keesj/.venv/lib/python3.12/site-packages/wavedrom/__init__.py", line 55, in main
    render_write(args.input, args.svg, False)
  File "/home/keesj/.venv/lib/python3.12/site-packages/wavedrom/__init__.py", line 37, in render_write
    out = render(jinput, strict_js_features=strict_js_features)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keesj/.venv/lib/python3.12/site-packages/wavedrom/__init__.py", line 28, in render
    return WaveDrom().render_waveform(0, source, output, strict_js_features)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keesj/.venv/lib/python3.12/site-packages/wavedrom/waveform.py", line 784, in render_waveform
    arcs = self.render_arcs(ret.lanes, index, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keesj/.venv/lib/python3.12/site-packages/wavedrom/waveform.py", line 590, in render_arcs
    frm = AttrDict(Events[Edge.frm])
                   ~~~~~~^^^^^^^^^^
KeyError: 'A'
```

It appears that wavedrompy  can not find the "A" label

**Comment by tarikgraba** [comment]
With a strict json the svg is correctly generated.

```json
{
  "signal": [
    {"name": "clk",            "wave": "p..pp......p"},
    {"name": "input_ready",    "wave":    "010.........", "node":"............"},
    {"name": "signalanalisys", "wave": "0...3....0.."   , "node":"............", "data": ["running"]},
    {                                                     "node":".A..B......."},
    {"name": "output_ready",   "wave":   "0........10."}
  ],
  "edge": [
    "A<->B delay"
  ]
}
```

**Comment by keesj** [comment]
Thank you for looking into this issue. This solves it for me. I was not aware of such a thing as strict json. I just followed the [Hitchhiker's Guide to the WaveDrom](https://wavedrom.com/tutorial.html) but now notice that the online examples of wavedrom also do not appear to be strict json (jq can not digest them) .   <img width="635" height="340" alt="Image" src="https://github.com/user-attachments/assets/f186ece7-8b19-4927-9dda-a475814220b2" />

**Comment by tarikgraba** [comment]
Yes, wavedrom uses relaxed json while wavedrompy strict json (because of the pytohn standard json parser).

https://github.com/wallento/wavedrompy?tab=readme-ov-file#important-notice

This is a known issue for which a solution has been implemented (even though it seems it does not always work as expected):

https://github.com/wallento/wavedrompy/issues/34
